# yaml-language-server: $schema=https://raw.githubusercontent.com/equinor/radix-operator/release/json-schema/radixapplication.json

#radixconfig production
apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: nils-oneseismic
spec:
  build:
    useBuildKit: true
  environments:
    # stable production branch users are supposed to use
    - name: prod
      build:
        from: radix
    # small resources environment
    - name: test
      build:
        from: radix_playground
    - name: test-large
      build:
        from: radix_test_large
  components:
    - name: server
      dockerfileName: Dockerfile
      runtime:
        architecture: arm64
      ports:
        - name: http
          port: 8080
        - name: metrics
          port: 8081
      publicPort: http
      monitoringConfig:
        portName: metrics
      environmentConfig:
        - environment: prod
          replicas: 0
        - environment: test
          replicas: 0
        - environment: test-large
          replicas: 0
